version: "3"
services:
  hub: 
    image: seleniarm/hub:4.10
    networks:
      - selenium-grid

  chrome:
    image: seleniarm/node-chromium:4.10
    shm_size: '1g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env
    networks:
      - selenium-grid

  firefox:
    image: seleniarm/node-firefox:4.10
    shm_size: '1g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env
    networks:
      - selenium-grid


networks:
  selenium-grid:
    driver: bridge
